version: "3.7"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
      - ./.docker/mysql/init.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - ./.docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js

  app:
    image: node:16
    working_dir: /workspace
    command: yarn start
    environment:
      MONGO_HOST: mongodb://mongo:27017
      DB_PASSWORD: mongoose
      DB_USER: root
      DB_HOST: mysql
      DB_NAME: library
    ports:
      - '8080:8080'
    volumes:
      - ./:/workspace
volumes:
  mysql_data:
  mongo_data:
